"openapi": "3.0.3"
"info":
  "title": "Pixel Playground"
  "version": "1.0.0"
  "contact": {}
"servers":
  - "url": "{{url}}"
"components":
  "securitySchemes":
    "BearerAuth":
      "type": "http"
      "scheme": "bearer"
      "bearerFormat": "JWT"
"security":
  - "BearerAuth": []
"paths":
  "/auth/register":
    "post":
      "tags":
        - "auth"
      "security": []
      "description": "Registers a new user (either a customer or a seller)"
      "operationId": "register"
      "requestBody":
        "content":
          "application/json":
            "examples":
              "seller":
                "value":
                  "email": "{{email}}"
                  "name": "{{name}}"
                  "password": "{{password}}"
                  "role": "seller"
              "customer":
                "value":
                  "email": "{{email}}"
                  "name": "{{name}}"
                  "password": "{{password}}"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    user_id: "bb6e3576-41b1-4584-96a0-ad3ba7fda970"
                    email: "hannipham@gmail.com"
                    created_at: "2024-12-08T04:20:08.812Z"
                    role_id: 3
  "/auth/login":
    "post":
      "tags":
        - "auth"
      "security": []
      "description": "Authenticates a user and gives a Bearer token back if it was successful"
      "operationId": "login"
      "requestBody":
        "content":
          "application/json":
            "examples":
              "login":
                "value":
                  "email": "{{email}}"
                  "password": "{{password}}"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYmI2ZTM1NzYtNDFiMS00NTg0LTk2YTAtYWQzYmE3ZmRhOTcwIiwicm9sZV9uYW1lIjoiQ3VzdG9tZXIiLCJuYW1lIjoiSGFubmkgUGhhbSIsImVtYWlsIjoiaGFubmlwaGFtQGdtYWlsLmNvbSIsImNyZWF0ZWRfYXQiOiIyMDI0LTEyLTA4VDA0OjIwOjA4LjgxMloiLCJpYXQiOjE3MzM2MzE3MjQsImV4cCI6MTczMzYzNTMyNH0._0D_Qs6FIFRd-H5La7sY8DsVtCuycqqUu64G2CQO0GQ"
  "/cart":
    "post":
      "tags":
        - "cart"
      "description": "Creates a new cart for a customer"
      "operationId": "createNewCart"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    cart_id: "b7596e46-4ced-48ef-a71a-3dc1b9f85bf7"
                    created_at: "2024-12-08T04:31:37.828Z"
    "get":
      "tags":
        - "cart"
      "description": "Returns the cart items of a customer"
      "operationId": "getCartItems"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    - quantity: 3
                      name: "NewJeans T-Shirt (Black)"
                      description: "Fire t-shirt"
                      price: 59.99
                      product_id: "49452e4c-522c-4c65-8c46-0fcbb0a76949"
                    - quantity: 2
                      name: "NewJeans T-Shirt (White)"
                      description: "Fire t-shirt"
                      price: 59.99
                      product_id: "f001919e-959c-4135-bb49-290d05273d9c"
  "/cart/{cartId}":
    "post":
      "tags":
        - "cart"
      "parameters":
        - "name": "cartId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
      "description": "Adds items into the cart"
      "operationId": "addItems"
      "requestBody":
        "content":
          "application/json":
            "examples":
              "add items":
                "value":
                  "items":
                    - "product_id": "{{uuid}}"
                      "quantity": 2
                    - "product_id": "{{uuid}}"
                      "quantity": 1
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    - cart_id: "b7596e46-4ced-48ef-a71a-3dc1b9f85bf7"
                      product_id: "49452e4c-522c-4c65-8c46-0fcbb0a76949"
                      quantity: 3
                    - cart_id: "b7596e46-4ced-48ef-a71a-3dc1b9f85bf7"
                      product_id: "f001919e-959c-4135-bb49-290d05273d9c"
                      quantity: 2
  "/cart/{cartId}/checkout":
    "post":
      "tags":
        - "cart"
      "parameters":
        - "name": "cartId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
      "description": "Checks out a cart of the user"
      "operationId": "checkout"
      "requestBody":
        "content":
          "application/json":
            "examples":
              "checkout":
                "value":
                  "address_id": "{{uuid}}"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    order_details:
                      order_id: "f0d0d659-9cde-47e9-ae76-1f851739f7dd"
                      customer_id: "bb6e3576-41b1-4584-96a0-ad3ba7fda970"
                      address_id: "dcba45d4-efef-4b16-80ee-22c6d5df4287"
                      status: "pending"
                      total_amount: 299.95
                      created_at: "2024-12-08T05:18:12.821Z"
                      updated_at: "2024-12-08T05:18:12.821Z"
                    order_items:
                      - quantity: 2
                        name: "NewJeans T-Shirt (White)"
                        description: "Fire t-shirt"
                        price: 59.99
                        product_id: "f001919e-959c-4135-bb49-290d05273d9c"
                      - quantity: 3
                        name: "NewJeans T-Shirt (Black)"
                        description: "Fire t-shirt"
                        price: 59.99
                        product_id: "49452e4c-522c-4c65-8c46-0fcbb0a76949"
  "/cart/{cartId}/{productId}":
    "put":
      "tags":
        - "cart"
      "parameters":
        - "name": "cartId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
        - "name": "productId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
      "description": "Updates the quantity of an item"
      "operationId": "updateQuantity"
      "requestBody":
        "content":
          "application/json":
            "examples":
              "update quantity":
                "value":
                  "quantity": "2"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    cart_id: "b7596e46-4ced-48ef-a71a-3dc1b9f85bf7"
                    product_id: "f001919e-959c-4135-bb49-290d05273d9c"
                    quantity: 2
    "delete":
      "tags":
        - "cart"
      "parameters":
        - "name": "cartId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
        - "name": "productId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
      "description": "Deletes an item from the cart"
      "operationId": "deleteItem"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    success: true
                    message: "Item deleted from cart"
  "/orders/":
    "get":
      "tags":
        - "orders"
      "description": "Returns all the orders of a user"
      "operationId": "getAllOrders"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    - order_details:
                      order_id: "e9b31ebd-0d7d-4dc9-8c86-8c11b7fd3064"
                      status: "pending"
                      total_amount: 299.95
                      created_at: "2024-12-08T05:15:27.053Z"
                      order_items:
                        - product_name: "NewJeans T-Shirt (White)"
                          quantity: 2
                          base_price: 59.99
                          total: 119.98
                        - product_name: "NewJeans T-Shirt (Black)"
                          quantity: 3
                          base_price: 59.99
                          total: 179.97
                    - order_details:
                        order_id: "f0d0d659-9cde-47e9-ae76-1f851739f7dd"
                        status: "pending"
                        total_amount: 299.95
                        created_at: "2024-12-08T05:18:12.821Z"
                      order_items:
                        - product_name: "NewJeans T-Shirt (White)"
                          quantity: 2
                          base_price: 59.99
                          total: 119.98
                        - product_name: "NewJeans T-Shirt (Black)"
                          quantity: 3
                          base_price: 59.99
                          total: 179.97
  "/orders/{orderId}":
    "get":
      "tags":
        - "orders"
      "parameters":
        - "name": "orderId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
      "description": "Returns the details of a specific order"
      "operationId": "getSpecificOrderDetails"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    order_details:
                      order_id: "f0d0d659-9cde-47e9-ae76-1f851739f7dd"
                      status: "pending"
                      total_amount: 299.95
                      created_at: "2024-12-08T05:18:12.821Z"
                    order_items:
                      - product_name: "NewJeans T-Shirt (White)"
                        quantity: 2
                        base_price: 59.99
                        total: 119.98
                      - product_name: "NewJeans T-Shirt (Black)"
                        quantity: 3
                        base_price: 59.99
                        total: 179.97
  "/products":
    "get":
      "tags":
        - "products"
      "description": "Returns all of the products within a given category"
      "operationId": "getAllProductsFromCategory"
      "parameters":
        - "name": "category"
          "in": "query"
          "schema":
            "type": "string"
            "example": "category_id"
        - "name": "perPage"
          "in": "query"
          "schema":
            "type": "string"
            "example": "10"
        - "name": "currentPage"
          "in": "query"
          "schema":
            "type": "string"
            "example": "2 (starts with 1)"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    - product_id: "49452e4c-522c-4c65-8c46-0fcbb0a76949"
                      seller_id: "8f96b95e-2da1-4516-aeb4-07d98db24877"
                      name: "NewJeans T-Shirt (Black)"
                      description: "Fire t-shirt"
                      price: 59.99
                      stock_quantity: 100
                      created_at: "2024-12-08T04:45:56.580Z"
                      updated_at: "2024-12-08T04:45:56.580Z"
                      category_id: 1
                      category_name: "Clothing"
                    - product_id: "f001919e-959c-4135-bb49-290d05273d9c"
                      seller_id: "8f96b95e-2da1-4516-aeb4-07d98db24877"
                      name: "NewJeans T-Shirt (White)"
                      description: "Fire t-shirt"
                      price: 59.99
                      stock_quantity: 100
                      created_at: "2024-12-08T04:46:18.152Z"
                      updated_at: "2024-12-08T04:46:18.152Z"
                      category_id: 1
                      category_name: "Clothing"
    "post":
      "tags":
        - "products"
      "description": "Adds a product listing"
      "operationId": "addProduct"
      "requestBody":
        "content":
          "application/json":
            "examples":
              "add product":
                "value":
                  "category_id": 1
                  "description": "{{description}}"
                  "name": "{{name of the product}}"
                  "price": 60
                  "stock_quantity": 100
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    product_id: "49452e4c-522c-4c65-8c46-0fcbb0a76949"
                    seller_id: "8f96b95e-2da1-4516-aeb4-07d98db24877"
                    name: "NewJeans T-Shirt (Black)"
                    description: "Fire t-shirt"
                    price: 59.99
                    stock_quantity: 100
                    created_at: "2024-12-08T04:45:56.580Z"
                    updated_at: "2024-12-08T04:45:56.580Z"
                    category_id: 1
  "/products/{productId}":
    "get":
      "tags":
        - "products"
      "parameters":
        - "name": "productId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
      "description": "Returns the details of a specific product"
      "operationId": "getProductDetails"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    product_id: "49452e4c-522c-4c65-8c46-0fcbb0a76949"
                    seller_id: "8f96b95e-2da1-4516-aeb4-07d98db24877"
                    name: "NewJeans T-Shirt (Black)"
                    description: "Fire t-shirt"
                    price: 59.99
                    stock_quantity: 100
                    created_at: "2024-12-08T04:45:56.580Z"
                    updated_at: "2024-12-08T04:45:56.580Z"
                    category_id: 1
                    category_name: "Clothing"
    "delete":
      "tags":
        - "products"
      "parameters":
        - "name": "productId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
      "description": "Deletes a specific product"
      "operationId": "deleteProduct"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    success: true
                    message: "Product successfully deleted"
    "put":
      "tags":
        - "products"
      "parameters":
        - "name": "productId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
      "description": "Updates a specific product"
      "operationId": "updateProduct"
      "requestBody":
        "content":
          "application/json":
            "examples":
              "update product":
                "value":
                  "name": "{{product name}}"
                  "price": 1000
                  "stock_quantity": 20
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    product_id: "49452e4c-522c-4c65-8c46-0fcbb0a76949"
                    seller_id: "8f96b95e-2da1-4516-aeb4-07d98db24877"
                    name: "NewJeans T-Shirt (Black)"
                    description: "Fire t-shirt"
                    price: 59.99
                    stock_quantity: 20
                    created_at: "2024-12-08T04:45:56.580Z"
                    updated_at: "2024-12-08T04:55:56.590Z"
                    category_id: 1
  "/users":
    "get":
      "tags":
        - "users"
      "parameters":
        - "name": "role_name"
          "in": "query"
          "schema":
            "type": "string"
            "example": "customer"
        - "name": "perPage"
          "in": "query"
          "schema":
            "type": "integer"
            "example": "10"
        - "name": "currentPage"
          "in": "query"
          "schema":
            "type": "integer"
            "example": "1"
      "description": "Returns all of the users of a specific role"
      "operationId": "getAllUsersWithRole"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    - user_id: "bb6e3576-41b1-4584-96a0-ad3ba7fda970"
                      name: "Hanni Pham"
                      email: "hannipham@gmail.com"
                      password_hash: "$2b$12$cT9b1pn6aLVpJSMaZ7eym.KC3/KSF35VR7ikTBwERZmcO.cmU3h5K"
                      created_at: "2024-12-08T04:20:08.812Z"
                      updated_at: "2024-12-08T04:20:08.812Z"
                      last_login: "2024-12-08T04:22:04.597Z"
                      role_id: 3
                      customer_id: "bb6e3576-41b1-4584-96a0-ad3ba7fda970"
                      date_of_birth: null
                      sex: null
                      loyalty_points: 100
                    - user_id: "1c69c97b-9f6f-41e5-91a4-a59994289fbb"
                      name: "Danielle Marsh"
                      email: "danidanidani@gmail.com"
                      password_hash: "$2b$12$R2IqpTU/2Zk/J5LkwrxVQeEkKbdRAHl/EQxOY7dhbS2JwVgki31Y."
                      created_at: "2024-12-08T05:46:32.258Z"
                      updated_at: "2024-12-08T05:46:32.258Z"
                      last_login: null
                      role_id: 3
                      customer_id: "1c69c97b-9f6f-41e5-91a4-a59994289fbb"
                      date_of_birth: null
                      sex: null
                      loyalty_points: null
  "/users/{userId}":
    "get":
      "tags":
        - "users"
      "parameters":
        - "name": "userId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
      "description": "Returns a user's details"
      "operationId": "getUserDetails"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    user_id: "bb6e3576-41b1-4584-96a0-ad3ba7fda970"
                    name: "Hanni Pham"
                    email: "hannipham@gmail.com"
                    password_hash: "$2b$12$cT9b1pn6aLVpJSMaZ7eym.KC3/KSF35VR7ikTBwERZmcO.cmU3h5K"
                    created_at: "2024-12-08T04:20:08.812Z"
                    updated_at: "2024-12-08T04:20:08.812Z"
                    last_login: "2024-12-08T04:22:04.597Z"
                    role_id: 3
                    customer_id: "bb6e3576-41b1-4584-96a0-ad3ba7fda970"
                    date_of_birth: null
                    sex: null
                    loyalty_points: null
    "put":
      "tags":
        - "users"
      "parameters":
        - "name": "userId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
      "description": "Update a user's details"
      "operationId": "updateUserDetails"
      "requestBody":
        "content":
          "application/json":
            "examples":
              "update customer details":
                "value":
                  "email": "{{email}}"
                  "password": "{{password}}"
                  "name": "{{name}}"
                  "date_of_birth": "{{date of birth}}"
                  "sex": "{{sex}}"
                  "loyalty_points": 100
              "update seller details":
                "value":
                  "email": "{{email}}"
                  "password": "{{password}}"
                  "name": "{{name}}"
                  "business_name": "{{business_name}}"
                  "phone_number": "{{phone number}}"
                  "description": "{{description}}"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    - user_id: "bb6e3576-41b1-4584-96a0-ad3ba7fda970"
                      name: "Hanni Pham"
                      email: "hannipham@gmail.com"
                      password_hash: "$2b$12$cT9b1pn6aLVpJSMaZ7eym.KC3/KSF35VR7ikTBwERZmcO.cmU3h5K"
                      created_at: "2024-12-08T04:20:08.812Z"
                      updated_at: "2024-12-08T04:20:08.812Z"
                      last_login: "2024-12-08T04:22:04.597Z"
                      role_id: 3
                      customer_id: "bb6e3576-41b1-4584-96a0-ad3ba7fda970"
                      date_of_birth: null
                      sex: null
                      loyalty_points: 100
  "/users/{userId}/addresses":
    "get":
      "tags":
        - "users"
      "parameters":
        - "name": "userId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
      "description": "Returns the addresses of a customer"
      "operationId": "getAddresses"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    - address_id: "dcba45d4-efef-4b16-80ee-22c6d5df4287"
                      customer_id: "bb6e3576-41b1-4584-96a0-ad3ba7fda970"
                      address_line_1: "123 NewJeans Rd"
                      address_line_2: null
                      city: "Incheon"
                      state: "IDK"
                      zipcode: "12345"
                      country: "South Korea"
                      phone_number: "123-456-7890"
                      is_default: false
                    - address_id: "f9a7748d-013d-40a7-ba4b-5ab0c466e969"
                      customer_id: "bb6e3576-41b1-4584-96a0-ad3ba7fda970"
                      address_line_1: "456 NewJeans Rd"
                      address_line_2: null
                      city: "Incheon"
                      state: "IDK"
                      zipcode: "12345"
                      country: "South Korea"
                      phone_number: "123-456-7890"
                      is_default: true
                    - address_id: "b5a126e9-c2a8-41b8-b11b-20e81d49ab20"
                      customer_id: "bb6e3576-41b1-4584-96a0-ad3ba7fda970"
                      address_line_1: "789 NewJeans Rd"
                      address_line_2: null
                      city: "Incheon"
                      state: "IDK"
                      zipcode: "12345"
                      country: "South Korea"
                      phone_number: "123-456-7890"
                      is_default: false
    "post":
      "tags":
        - "users"
      "parameters":
        - "name": "userId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
      "description": "Adds a new address for a customer"
      "operationId": "addNewAddress"
      "requestBody":
        "content":
          "application/json":
            "examples":
              "add new address":
                "value":
                  "address_line_1": "{{address line 1}}"
                  "address_line_2": "{{address line 2 (optional)}}"
                  "city": "{{city}}"
                  "country": "{{country}}"
                  "phone_number": "{{phone_number}}"
                  "state": "{{state}}"
                  "zipcode": "{{zipcode}}"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    address_id: "dcba45d4-efef-4b16-80ee-22c6d5df4287"
                    customer_id: "bb6e3576-41b1-4584-96a0-ad3ba7fda970"
                    address_line_1: "123 NewJeans Rd"
                    address_line_2: null
                    city: "Incheon"
                    state: "IDK"
                    zipcode: "12345"
                    country: "South Korea"
                    phone_number: "123-456-7890"
                    is_default: true
  "/users/{userId}/addresses/{addressId}":
    "put":
      "tags":
        - "users"
      "parameters":
        - "name": "userId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
        - "name": "addressId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
      "description": "Updates an address"
      "operationId": "updateAddress"
      "requestBody":
        "content":
          "application/json":
            "examples":
              "update address":
                "value":
                  "address_line_1": "{{address line 1}}"
                  "address_line_2": "{{address line 2 (optional)}}"
                  "city": "{{city}}"
                  "country": "{{country}}"
                  "phone_number": "{{phone_number}}"
                  "state": "{{state}}"
                  "zipcode": "{{zipcode}}"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    address_id: "f9a7748d-013d-40a7-ba4b-5ab0c466e969"
                    customer_id: "bb6e3576-41b1-4584-96a0-ad3ba7fda970"
                    address_line_1: "456 NewJeans Rd"
                    address_line_2: null
                    city: "Incheon"
                    state: "IDK"
                    zipcode: "12345"
                    country: "South Korea"
                    phone_number: "123-456-7890"
                    is_default: true
    "delete":
      "tags":
        - "users"
      "parameters":
        - "name": "userId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
        - "name": "addressId"
          "in": "path"
          "required": true
          "schema":
            "type": "string"
      "description": "Deletes an address"
      "operationId": "deleteAddress"
      "responses":
        "200":
          "description": "Successful response"
          content:
            application/json:
              examples:
                default:
                  value:
                    success: true
                    message: "Address deleted successfully"
"tags":
  - "name": "auth"
  - "name": "cart"
  - "name": "orders"
  - "name": "products"
  - "name": "users"
